/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int MULTIPLY = 4;
  /** RegularExpression Id. */
  int DIVIDE = 5;
  /** RegularExpression Id. */
  int INCR = 6;
  /** RegularExpression Id. */
  int DECR = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int LE = 9;
  /** RegularExpression Id. */
  int MN = 10;
  /** RegularExpression Id. */
  int GE = 11;
  /** RegularExpression Id. */
  int GR = 12;
  /** RegularExpression Id. */
  int NE = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int LBRACE = 18;
  /** RegularExpression Id. */
  int RBRACE = 19;
  /** RegularExpression Id. */
  int LBRACKET = 20;
  /** RegularExpression Id. */
  int RBRACKET = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int DOUBLECOMMA = 25;
  /** RegularExpression Id. */
  int PUBLIC = 26;
  /** RegularExpression Id. */
  int PRIVATE = 27;
  /** RegularExpression Id. */
  int STATIC = 28;
  /** RegularExpression Id. */
  int VOID = 29;
  /** RegularExpression Id. */
  int MAIN = 30;
  /** RegularExpression Id. */
  int PROGRAMA = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int ELSEIF = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int SWITCH = 36;
  /** RegularExpression Id. */
  int CASE = 37;
  /** RegularExpression Id. */
  int BREAK = 38;
  /** RegularExpression Id. */
  int DEFAUL = 39;
  /** RegularExpression Id. */
  int DO = 40;
  /** RegularExpression Id. */
  int WHILE = 41;
  /** RegularExpression Id. */
  int WRITE = 42;
  /** RegularExpression Id. */
  int READ = 43;
  /** RegularExpression Id. */
  int FIN = 44;
  /** RegularExpression Id. */
  int INT = 45;
  /** RegularExpression Id. */
  int DEC = 46;
  /** RegularExpression Id. */
  int CHR = 47;
  /** RegularExpression Id. */
  int STR = 48;
  /** RegularExpression Id. */
  int NUMBER = 49;
  /** RegularExpression Id. */
  int IDENTIFIER = 50;
  /** RegularExpression Id. */
  int DECIMAL = 51;
  /** RegularExpression Id. */
  int CADENA = 52;
  /** RegularExpression Id. */
  int CARAC = 53;
  /** RegularExpression Id. */
  int DOUBLEPOINT = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"++\"",
    "\"--\"",
    "\"==\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"\\\"\"",
    "\"publico\"",
    "\"privado\"",
    "\"estatico\"",
    "\"vacio\"",
    "\"principal()\"",
    "\"programa\"",
    "\"si\"",
    "\"o_si\"",
    "\"sino\"",
    "\"repetir\"",
    "\"alternativas\"",
    "\"opcion\"",
    "\"salir\"",
    "\"defecto\"",
    "\"realice\"",
    "\"ciclo\"",
    "\"imprima\"",
    "\"lea\"",
    "\"fin\"",
    "\"numero\"",
    "\"decimal\"",
    "\"caracter\"",
    "\"cadena\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<DECIMAL>",
    "<CADENA>",
    "<CARAC>",
    "\":\"",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
